<!DOCTYPE html>	
<html>	  
  <head>  
    <title>{% if page.title %} {{ page.title }} | {% endif %} JacobMartin.org</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="/css/main.css">
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
	<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  </head>
  <body>
	<div id="top">
	  <div id="logo">
		<a href="/"><img src="/images/logo.png" alt="Jacob Martin" width="320"></a>
	  </div>
	  <nav>
		<div id="topnav">
		  <ul class="navigation">
			<li><a href="/">Home</a></li>
			<li><a href="/about.html">About</a></li>
			<li><a href="/copyright.html">Legal</a></li>
			<li><a href="http://www.flickr.com/photos/leitzkameraaktion/">Flickr</a></li>
		  </ul>
		</div>
		<div style="clear: both;"></div>
	  </nav>
	</div>
	<div id="lowerpage">
	  <div id="content">
